[workspace]
resolver = "2"
members = ["redirector", "ipc"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
prost = "0.14"
prost-build = "0.14"
protoc-bin-vendored = "3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_IO",
    "Win32_System_Memory",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
] }

[profile.release]
lto = "thin"
strip = true
